workflows:
  yoma_release:
    name: YOMA - Android & iOS Release
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        PACKAGE_NAME: "com.patriciagiorgetto.yoma"
      groups:
        - keystore_credentials
        - ios_credentials
    scripts:
      - name: 🧹 Clean Project
        script: |
          flutter clean
          flutter pub get

      - name: 🔐 Decode Android Keystore
        script: |
          echo $KEYSTORE_BASE64 | base64 --decode > /tmp/keystore.jks
          export CM_KEYSTORE_PATH=/tmp/keystore.jks

      - name: 🤖 Build Android AAB
        script: |
          flutter build appbundle --release

      - name: 🍏 Decode iOS Certificates
        script: |
          echo $CERTIFICATE_P12 | base64 --decode > /tmp/certificate.p12
          echo $PROVISIONING_PROFILE | base64 --decode > /tmp/profile.mobileprovision

      - name: 🍎 Build iOS IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=ios/Runner/ExportOptions.plist

    artifacts:
      - build/app/outputs/bundle/release/*.aab
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - "patriciagiorgetto@hotmail.com"
